apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jenkins
  ports:
    - name: master
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
    - name: slave
      port: {{ .Values.service.ports.jnlp }}
      targetPort: {{ .Values.service.ports.jnlp }}
