namespace: ci-cd

image:
  repository: jfrog.it-academy.by/public/jenkins-ci
  tag: true.devops_32
  pullPolicy: IfNotPresent

secret:
  password: "XXXXX"

resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 3
    memory: 3Gi

service:
  ports:
    http: 8080
    jnlp: 50000

ingress:
  enabled: true
  ingressClassName: nginx
  host: jenkins.k8s-5.sa
