apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: {{ .Values.jenkins.image }}
        imagePullPolicy: {{ .Values.jenkins.pullPolicy }}
        ports:
        - containerPort: {{ .Values.jenkins.httpPort }}
        - containerPort: {{ .Values.jenkins.jnlpPort }}
        resources:
          requests:
            cpu: {{ .Values.jenkins.cpuRequest }}
            memory: {{ .Values.jenkins.memoryRequest }}
          limits:
            cpu: {{ .Values.jenkins.cpuLimit }}
            memory: {{ .Values.jenkins.memoryLimit }}
        env:
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: password
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc_configs/jenkins.yaml
        volumeMounts:
        - name: jenkins-config
          mountPath: /var/jenkins_home
        - name: jenkins-config-yaml
          mountPath: /var/jenkins_home/casc_configs/jenkins.yaml
          subPath: jenkins.yaml
        - name: jenkins-auth-config
          mountPath: /var/jenkins_home/init.groovy.d/basic-security.groovy
          subPath: basic-security.groovy
      volumes:
      - name: jenkins-config
        emptyDir: {}
      - name: jenkins-config-yaml
        configMap:
          name: jenkins-config
      - name: jenkins-auth-config
        configMap:
          name: basic-security
