name: Check pods on private clusters

on:
  push:
    branches:
      - master

jobs:
  check_pods:
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Check pods on k3s cluster
        run: |
          count=$(kubectl get pods -A --context=k3s -o jsonpath='{range .items[*]}{.status.phase}{"\n"}{end}' | grep -v Running | wc -l)
          echo "Crashed pods in k3s: $count"
          if [ "$count" -ne 0 ]; then
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"🚨 $count crashed pods in k3s cluster.\"}" $SLACK_WEBHOOK_URL
          fi
