name: Check pods on private clusters

on:
  push:
    branches:
      - master

jobs:
  check_pods:
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Check pods on k8s cluster
        run: |
          running_pods=$(kubectl get pods -A --context=k8s --field-selector=status.phase=Running -o jsonpath='{range .items[*]}{.metadata.namespace}/{.metadata.name}{"\n"}{end}')
          echo "Running pods in k8s:"
          echo "$running_pods"

          if [ -n "$running_pods" ]; then
            message="✅ Running pods in k8s cluster:\n$running_pods"
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" $SLACK_WEBHOOK_URL
          fi
