name: Check err pods on private clusters

on:
  push:
    branches:
      - master

jobs:
  check_pods:
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Check crashed pods on k3s cluster
        run: |
          crash_pods=$(kubectl get pods -A --context='k3s' | awk 'NR!=1 {print $4}' | grep -v 'Running' | wc -l)
          echo "Crashed pods in k3s: $crash_pods"
          if [ "$crash_pods" -ne 0 ]; then
            curl -X POST -H 'Content-type: application/json' \
                 --data "{\"text\":\"🚨 $crash_pods crashed pods in k3s cluster.\"}" \
                 "$SLACK_WEBHOOK_URL"
          fi
