name: B and P_DI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Логин в Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Сборка и пуш Docker образа
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: maktrue/mygoapp:latest

    - name: Уведомление в Slack об успешной сборке
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":":white_check_mark: Docker образ mygoapp:latest успешно собран и запушен!"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Уведомление в Slack при ошибке сборки
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":":x: Сборка или пуш Docker образа mygoapp:latest завершились с ошибкой!"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
