name: KinD Cluster Setup

on:
  push:
    branches:
      - master

jobs:
  setup-kind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install KinD
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Create KinD cluster
        run: |
          kind create cluster --name github-actions

      - name: Get cluster info
        run: |
          kubectl cluster-info
          kubectl get nodes
