apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"ubuntu"},"name":"ubuntu-default","namespace":"default"},"spec":{"containers":[{"command":["sleep","604800"],"image":"ghcr.io/pluhin/busy-box:latest","imagePullPolicy":"IfNotPresent","name":"ubuntu-default"}]}}
  creationTimestamp: "2025-08-10T01:45:06Z"
  generation: 1
  labels:
    app: ubuntu
  name: ubuntu-default
  namespace: default
  resourceVersion: "21813"
  uid: 12a9d580-b2d2-4773-9a5f-c63e4e7fbc15
spec:
  containers:
  - command:
    - sleep
    - "604800"
    image: ghcr.io/pluhin/busy-box:latest
    imagePullPolicy: IfNotPresent
    name: ubuntu-default
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qnmmk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: debian10
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-qnmmk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-10T01:45:28Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-10T01:45:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-10T01:45:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-10T01:45:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-10T01:45:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://284e9c0f34fa699e558fe8b6a45d030c53b114a513e6b8e1072c933c2a06fa06
    image: ghcr.io/pluhin/busy-box:latest
    imageID: ghcr.io/pluhin/busy-box@sha256:1424a6223bc15fc40d3bb4c5b2956fd615c967156ba6d55ea338dcc8e9d2103d
    lastState: {}
    name: ubuntu-default
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-10T01:45:28Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qnmmk
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.203.3
  hostIPs:
  - ip: 192.168.203.3
  phase: Running
  podIP: 10.42.0.5
  podIPs:
  - ip: 10.42.0.5
  qosClass: BestEffort
  startTime: "2025-08-10T01:45:06Z"
