name: Run Python program!
on:
  push:
    branches: [master]
jobs:
  run-str:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: Run script PY
         run: python3 string.py
