name: Run Python program!
on:
  push:
    branches: [master]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: Run script main
         run: python3 main.py
       - name: Run script tests
         run: python3 test_main.py
